from main import *
Game = HangmanSolver()
Game.new_game("VUlCÃO", 10)
print(Game.make_guess())
Game.filter_negative("A")
print(Game.make_guess())
Game.filter_positive("E***E*E***")
print(Game.make_guess())
Game.filter_positive("E***E*E*O*")
print(Game.make_guess())
Game.filter_positive("ES**E*E*O*")
print(Game.make_guess())
Game.filter_positive("ES**E*EDO*")
print(Game.make_guess())
Game.filter_positive("ES**EMEDO*")
print(Game.make_guess())
Game.filter_positive("ESP*EMEDO*")
print(Game.make_guess())